### ISSUE TITLE
Code Examples

### ISSUE THREAD

**Issue by robjnavy** [Sento/dragula-rails#1]
Sento,

Do you have any code examples of integrating this into a rails project?

**Comment by zedtux** [comment]
Hello @robjnavy,

Thank you for your issue.

First point, the named gem `dragula-rails` is maintained by [why-el](https://github.com/why-el) in [this repo](https://github.com/why-el/dragula-rails).
This repo is a fork.

Now you can have a look at [sento-kaban](https://github.com/Sento/sento-kanban), our open source project, where we're using it.

1. After the page of columns and cards is loaded [we're calling a JavaScript helper function](https://github.com/Sento/sento-kanban/blob/master/app/views/sento/kanban/boards/show.js.erb#L4) we built called `applyDragula()` (which is defined in the [`app/assets/javascripts/sento/kanban/helpers/apply-dragula.js`](https://github.com/Sento/sento-kanban/blob/master/app/assets/javascripts/sento/kanban/helpers/apply-dragula.js) file)
2. In this function [we are passing to dragular all the cards](https://github.com/Sento/sento-kanban/blob/master/app/assets/javascripts/sento/kanban/helpers/apply-dragula.js#L7) using `$('.sento-kanban-cards').toArray()`
3. [With the `drop` event](https://github.com/Sento/sento-kanban/blob/master/app/assets/javascripts/sento/kanban/helpers/apply-dragula.js#L9) we are updating some `data` attributes and then calling an Ajax call in order to submit the cards position update.

I hope this will help you :)
